modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
[[mods]]
modId="redstoneutils"
version="${file.jarVersion}"
displayName="Redstone Utils"
logoFile="examplemod.png"
authors="Razzokk"
description='''A utilities mod that adds various redstone components'''

[[dependencies.redstoneutils]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.redstoneutils]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
